### ISSUE TITLE
[PyCon] TODO List

### ISSUE THREAD

**Issue by Bubobubobubobubo** [Bubobubobubobubo/sardine#162]
This is a TODO list of the things to work on during the PyCon event next week. They come in no specific order. Most probably, one branch should be opened to deal with each issue separately. All of these tasks are doable in a two day timespan given that we attack this with method and care.

**Easy fixes** 

- [ ] (**JS**) Toggle history in Fishery Web.
- [x] Survival kit overhaul
    - [x] Explain what sample numbers are
    - [x] Do not use `i` right away, explain what it does before.
- [x] The experimental GUI is not properly creating the logging file. The mechanism for creating the file is there but it is reached too late, way after the file is required.
- [x] Rework attributes, especially those concerning clock and nudge. Some are still on the private side and cannot be easily invoked by users. This is just a matter of adding a getter/setter!
- [ ] Switch current printing to `logging`. Precision can be added in the logging information.
- [x] Make it so that Flask doesn't print anything and stops dumping info into the REPL. Flask loves printing stuff, and we mostly don't care. Additionally, add a dev switch for actually printing when we need to.
- [x] Remove the boxes around AsyncRunner information. Something more lightweight as replacement.
- [x] Promote the `OSC._send` function to public function as it can be useful for some perfomers.

**Intermediate fixes**

- [x] (**JS**) Add a key for block evaluation, different from the selection evaluation.
- [x] (**JS**) Log printing in the web interface can kill the web browser (if the printing is too busy). This is only true for exceptionally fast operations but it can happen!
    - can it be because the log reading library is synchronous and everything else async?
    - can we improve the log reading mechanism? make it faster?
- [x] (**JS**) Changing the internal buffer will toggle a weird behavior when inserting new lines or deleting characters. Each of these operations is essentially repeated, making two new lines appear or deleting two characters.
    - The fix has been introduced by @JMPothelune in #163. 
- [ ] (**JS**) Allow the user to pick a font and and a theme (no contextual menu anywhere, it should be a command of some sort). All the themes should be dark mode! We need a black neutral background for projecting the screen on walls.
    - For no good reason at all, we **STRONGLY** encourage using monospace serif fonts.
    - No ugly themes or weird color mix. This is subjective but I guess that there is some common knowledge about what good colors are! 
- [x] Sardine X Ziffers implementation (https://github.com/Bubobubobubobubo/ziffers-python). Adding the base implementation + the surfboard syntax for playing with Ziffers patterns. We might need handlers for MIDI and SuperDirt. 
    - [x] Remove the infrastructure that was prepared for Ziffers. We won't need it!
    - [ ] Adding the SuperDirt prototype handler
    - [x] Breaking it down, simplifying. Adding the MIDI version.
- [ ] Global storage for OSC messages and more control over the formatting of OSC messages (this was particularly important for some past experiments).
    - [ ] Recall up to 100 past OSC messages.

**Hard Fixes**

- [x] Implementation and documentation of conditional patterning in the base parser.
     - [x] can we make it less verbose? 
     - [ ] can we make it more powerful?
     - [ ] can we support high-order functions?
- [x] Fixing bugs and maintaining the base parser.
     - [ ] Typing everything won't hurt!
- [x] Rewriting / Refactoring of the base documentation!
     - [x] Shorter, faster, stronger.
     - [x] Documentation included in editor (**JS**). 
- [ ] (**JS**) Bundle / wrap Sardine for easy distribution and installation on any platform. This work is currently under way but some users still complain (mostly because their local environment is not clearly / properly managed). This is more like a Python issue but we have to fix it ourselves!
     - [ ] (**JS**) Bundle the `build` folder only for releases on Pypi!
- [ ] Performance fine tuning. Doing less.. making the timing system more introspectable.

**Open tasks**

- [ ] Working on a new audio engine to replace / complement SuperDirt. It should ideally do the same thing. Used to demonstrate that Sardine can adapt to multiple targets!
- [ ] Integration with CSound (would be great!) or WebAudio (would be great as well!).
- [x] (**JS**) Cosmetic improvements to the editor. Performance fine tuning.
- [ ] Rewrite Sardine Config using the wooonderful Textual package?

**Final task**

- [ ] Prepare a new release (`v.0.2.3`) for release on Pypi. This release should include the build version of the experimental editor and the conditional patterning.

**Comment by johnchem** [comment]
Following the PyConFR sprint, i'll continue to transfert the print statement into logging lib commands. 
Should i create an issue to follow this task ?

**Comment by Bubobubobubobubo** [comment]
Hi! 

Yes, this is probably the best way to proceed with this :)
